### ISSUE TITLE
US : Supprimer un calendrier

### ISSUE THREAD

**Issue by hugotnbx** [Nini1551/T304-Projet-Integration_IziClock#20]
En tant qu'utilisateur je souhaite pouvoir supprimer un calendrier précédemment synchroniser  afin de maintenir à jour mes sources de calendrier et de retirer les calendriers obsolètes
  
### Valeur pour le client
Cela permettra au client de pouvoir gérer efficacement ses calendriers en supprimant ceux qui ne sont plus nécessaires et évitant ainsi des alarmes sur des évènements non pertinents.

### Description
L'utilisateur pourra sélectionner un calendrier précédemment importé  et le supprimer de l'application. Cela permettra de supprimer toutes les données liées à ce calendrier tout en s'assurant que les autres calendriers et leurs évènements restent intacts.

### Maquettes
INSERER PHOTOS ET SCHEMAS

### Critères d'acceptation
* L'utilisateur peut accéder à une liste des calendriers synchronisés et en sélectionner un pour le supprimer
* Un message de confirmation est affiché avant la suppression afin d'éviter les mauvaises manipulations
* Après suppression, les évènements et alarmes liés à ce calendrier sont également supprimés

### Analyse technique
* Assurer la désynchronisation avec l'api de calendrier
* Mettre en place un processus pour supprimer les alarmes ou notifications liées aux évènements du calendrier préalablement supprimé.

### Tâches techniques
* [US-TT : Affichage d'une liste des calendriers](https://github.com/Nini1551/T304-Projet-Integration_IziClock/issues/29)
* [US-TT : Suppression d'un calendrier](https://github.com/Nini1551/T304-Projet-Integration_IziClock/issues/30)
* [US-TT : Confirmation de la suppression d'un calendrier](https://github.com/Nini1551/T304-Projet-Integration_IziClock/issues/32)
* [US-TT : Changement de l'état d'activité d'un calendrier](https://github.com/Nini1551/T304-Projet-Integration_IziClock/issues/33)
* [US-TT : Suppression des alarmes/événements liés au calendrier supprimé](https://github.com/Nini1551/T304-Projet-Integration_IziClock/issues/34)

**Comment by Nini1551** [comment]
Les critères de validation sont passés et l'US est respectée.
De mon coté, je rajouterais 2 choses avant de merge :

Ajouter un style qui permet directement de reconnaitre un calendrier actif d'un inactif. Par exemple, les calendriers inactifs pourrait être grisés (ou avoir une opacité réduite).
Il pourrait être interessant de classer les calendriers sur 2 choses : leur activité (les actifs avant les inactifs) et leur date de création (d'ajout dans la DB)
Veux-tu bien t'en occuper ?
Sinon, je peux le faire. Et si tu détermines que mes critiques ne sont pas utiles, tu peux les ignorer et merge.

**Comment by hugotnbx** [comment]
Les 2 points relevés lors de la review ont été réalisés.
