### ISSUE TITLE
US-TT : Suppression d'un calendrier

### ISSUE THREAD

**Issue by hugotnbx** [Nini1551/T304-Projet-Integration_IziClock#30]
TT lié à [US : Supprimer un calendrier](https://github.com/Nini1551/T304-Projet-Integration_IziClock/issues/20)

Implémenter la fonctionnalité de suppression d'un calendrier

**Comment by Nini1551** [comment]
Petit rappel : Lorsqu'on applique un changement à une table de la DB, il faut lui donner une valeur par défaut. Sinon, comme ici, le développeur est obligé de supprimer manuellement les lignes de sa table.

**Comment by Nini1551** [comment]
Les critères de validation sont passés et l'US est respectée.
De mon coté, je rajouterais 2 choses avant de merge : 
* Ajouter un style qui permet directement de reconnaitre un calendrier actif d'un inactif. Par exemple, les calendriers inactifs pourrait être grisés (ou avoir une opacité réduite).
* Il pourrait être interessant de classer les calendriers sur 2 choses : leur activité (les actifs avant les inactifs) et leur date de création (d'ajout dans la DB)
  
Veux-tu bien t'en occuper ? 
Sinon, je peux le faire. Et si tu détermines que mes critiques ne sont pas utiles, tu peux les ignorer et merge.
