### ISSUE TITLE
US : Accéder à une liste des alarmes

### ISSUE THREAD

**Issue by hugotnbx** [Nini1551/T304-Projet-Integration_IziClock#6]
## Accès à la liste des alarmes

En tant qu'utilisateur, je souhaite pouvoir accéder à une liste de mes alarmes afin de consulter mes événements de la journée.

### Valeur pour le client
Le client peut facilement consulter tous ses événements de la journée et vérifier si les alarmes correspondantes sont activées ou désactivées.

### Description
Une interface affichant tous les événements de la journée, avec un indicateur pour chaque alarme, précisant si elle est activée ou désactivée.

#### Maquettes
INSÉRER PHOTOS ET SCHÉMAS

### Critères d'acceptation
- Tous les événements de la journée sont affichés.
- L'état des alarmes (activée/désactivée) est clairement indiqué pour chaque événement.

### Analyse technique
À REMPLIR

### Tâches techniques
- Tâche 1 : Concevoir l'interface de la liste des alarmes.
- Tâche 2 : Implémenter la logique de récupération des événements de la journée.
- Tâche 3 : Afficher l'état des alarmes pour chaque événement.

**Comment by Nini1551** [comment]
## Etat de l'US pour la première mise en preview (10/10/24)

* Une liste d'alarmes mockées est reprise d'une base de données pour être envoyée via une API sur une plateforme pour être visualisée. Elles sont classées de la plus récente à la plus vieille.
* Chaque alarme affiche sont nom ainsi que sa date et son heure de sonnerie. Une alarme verte est activée tandis qu'une alarme rouge ne l'est pas.
  
## Remarques / A Travailler
* Les tests ne sont pas rédigés.
* La partie server n'est pas bien organisée. J'ai besoin d'un retour pour travailler là-dessus.
